---
title: "Skills Passport report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(dplyr)
# install.packages("kableExtra")
library(kableExtra)
source("d:/git/skills-passport/local.R")

```

# `r class_name` (`r length(students)` students)

`r format(Sys.time(),'%A, %B %d, %Y')`

This report lists the competencies we have recorded for each student in the selected cohort. 

```{r import_data,echo=FALSE}

# load the competency list. This will need to be updated from the competencies spreadsheet if any skills are added
competencies <- read.csv("d:/git/skills-passport/data/competencies.csv")

# store the competency code in the "Competency" column (replaces the barcode which is of no use here)
competencies$Competency <- competencies$Code

# highlight the "essential" competencies with a new column
competencies$E <- ""
competencies[competencies$Competency.classification=="essential","E"] <- "E"
competencies[competencies$Competency.classification=="specialist","E"] <- "S"
#competencies[competencies$Competency.classification=="desirable","E"] <- "D"

# Format of the competencies file: (as CSV)
## Code	Competency	Competency description	Competency classification	skill group	type
## PSH01	*PSH01*	Use an automatic pipette for volumes between 100ul – 1000 ul	essential	Pipetting and sample handling	technical
## PSH02	*PSH02*	Use an automatic pipette for volumes between 1ul – 10 ul	desirable	Pipetting and sample handling	technical
## PSH03	*PSH03*	Use a serological pipette for volumes between 5 ml – 25 ml	desirable	Pipetting and sample handling	technical

# The competencies are followed by module and programme specific information, 
# but I plan to move this out into a different file to make system more flexible
# Then, the programme / module can be specified at run time to make customised reports

# Load ID mapping - this is needed because student badge numbers or other identifiers might not be the same as student ID
ID_mapping <- read.csv("d:/git/skills-passport/data/ID_mapping/ID_mapping.csv")

# we will refine the student list to the ones we have data for. But keep the full list for reporting later
students.all <- students

# Filter by the selected class, if one is defined
if(length(students)>0) {
  ID_mapping <- ID_mapping[ID_mapping$student_ID%in%students,]
  students <- ID_mapping$student_ID
}

# Make sure we report on each student only once.
students <- unique(students)

# Identify the student IDs for which we do not have mapping information:
no_mapping <- students.all[!students.all%in%students]

# subset to records of interest for a report
# ID_mapping <- ID_mapping[88:nrow(ID_mapping),]

scanner_reads <- ldply(list.files("d:/git/skills-passport/data/scans",full.names = T,recursive = T), read.csv, header=FALSE)

# The format of the scanner files is like this (CSV):
## PSH09	Code-39	11:10:05	07/10/2022	19:20:16	18/12/2023	998826
## P201544022	Code-39	11:10:07	07/10/2022	19:20:16	18/12/2023	998826
# There are no headers in the file - see below for the column contents
# the scheme of use is that the teacher scans the competency barcode then the student card
# So in this example, the student P201544022 has been observed doing the competency PSH09

# discard extra columns
scanner_reads <- scanner_reads[,1:7]

# name some columns
# Note that the scans of student cards do not contain the student ID, we will need to match that up later
# it only contains the card number which probably changes if the card is lost and re-issued
names(scanner_reads)[1] <- "scan"
names(scanner_reads)[2] <- "format" 
names(scanner_reads)[3] <- "time"
names(scanner_reads)[4] <- "date"
names(scanner_reads)[5] <- "download_date"
names(scanner_reads)[6] <- "download_time"
names(scanner_reads)[7] <- "scanner"

# keep only unique entries
scanner_reads <- distinct(scanner_reads,scanner_reads[,1:4])

# make a column for recording the competency on each scan - to be populated later
scanner_reads$observed_competency <- "none"

# make a column for storing the date/time of scan
scanner_reads$datetime <- as.POSIXct(Sys.time())

# load data from manual records e.g. based on attendance or hardcopy sheet
# The required format is that the ID column and observed competency match up with the format of "matched records"
# which is created later on. Note that the ID column from attendance records will typically be the student ID 
# which is different from the barcode, plus we do not have scans of the skills barcodes so we import manual records differently.

# Required headings in the manual file: observed_competency, student_ID
manual <- ldply(list.files("d:/git/skills-passport/data/manual",full.names = T), read.csv, header=TRUE)
```



```{r process,results="asis",echo=FALSE}

show_extras <- 0
if(show_extras) {
  print(knitr::kable(ID_mapping, format="html"))
}
# read through the scans and assign a competency to the student scans
# based on the last scanned competency
# whilst we are at it also assign a datetime to each record
for(i in 1:nrow(scanner_reads)){
  if(scanner_reads[i,1]%in%competencies$Competency) {this_competency <- scanner_reads[i,1]}
  scanner_reads$observed_competency[i] <- this_competency
  t <- paste(scanner_reads$date[i],scanner_reads$time[i],sep="")
  scanner_reads$datetime[i] <- strptime(t,format=" %Y-%m-%d %I:%M:%S %p")
}

# delete the scanner reads of the competency barcodes that have now been applied to the records
scanner_reads <- scanner_reads[!scanner_reads$scan%in%competencies$Competency,]

# match up card scans to students
colnames(scanner_reads)[1] <- "Badge.Number"
scanner_reads2 <- merge(scanner_reads,ID_mapping,by.x = "Badge.Number",by.y = "Badge.Number",all = TRUE)

# Identify any unmatched reads - where we have the card ID but not the student ID
unmatched_reads <- scanner_reads2[is.na(scanner_reads2$Name),]
# set some of the fields to make this obvious in output:
unmatched_reads$name <- paste("Unknown - badge number ",unmatched_reads$Badge.Number)
unmatched_reads$student_ID <- paste("Unknown - badge number ",unmatched_reads$Badge.Number)
# Where we don't have a mapping of student ID/name to the card number
# replace the name to indicate this

scanner_reads2[is.na(scanner_reads2$Name),"Name"] <- "unknown"

matched_reads <- scanner_reads2
#matched_reads <- scanner_reads2[!is.na(scanner_reads2$Name),]
#matched_reads <- matched_reads[!is.na(matched_reads$observed_competency),]

# Simplifying the addition of manual reads. Use only the competency and the student ID
manual <- manual[!is.na(manual$student_ID),c("observed_competency","student_ID")]

# we now have matched and unmatched reads ready for reporting which should be done per student by the student ID number
# First, add any manual records e.g. from attendance data
matched_reads <- rbind.fill(matched_reads,manual)
# Now add the unmatched reads too, so we at least then get the output of the badge number report
# Note that this can take a long time to run because it will include a lot of unmatched records.
# so, it can be selected in local options file.

if(include_unmatched_badges) {
  matched_reads <- rbind.fill(matched_reads,unmatched_reads)
}
#matched_reads <- merge(matched_reads,manual,all.x = TRUE)
matched_reads_competencies <- merge(matched_reads,competencies,by.x = "observed_competency",by.y = "Competency")

# there are more student IDs in the matched reads than in our list of students
# This should not be, requires investigation. For now, remove the ones that don't belong in the output@
#unique(matched_reads_competencies$student_ID)
#students
matched_reads_competencies <- matched_reads_competencies[matched_reads_competencies$student_ID%in%students,]


# change some column names for clearer outputs
colnames(matched_reads_competencies)[c(1,12)] <- c("code", "competency")

# keep only unique records. There might be an error leading to duplications, requires investigation.
matched_reads_competencies <- distinct(matched_reads_competencies,matched_reads_competencies[,c(1,2,5)],.keep_all = T)

student_info <- 1

# report on students for which we have no badge number:
cat("We are unable to report on the following student IDs because the badge number is not known:\n",no_mapping,"\n\n")

# pull out the records and make a report for each student
skills_list <- unique(competencies$skill.group)

# for testing:
student <- students[1]

# report on the students that are in the student list
# which is defined in local.R
for(student in students) {
  s_name <- ID_mapping[ID_mapping$student_ID==student,"Name"][1]  
  s_email <- ID_mapping[ID_mapping$student_ID==student,"Email"][1]
  
  # identify skills
  student_competencies <- matched_reads_competencies[matched_reads_competencies$student_ID==student,c("code","date","E", "skill.group","Competency.description","Badge.Number")]
  
  # re-name columns for output
  colnames(student_competencies) <- c("code","date","E", "skill.group","description","Badge.Number")
  
  # there are lots of NAs, remove. Must be something wrong to introduce them.
  student_competencies <- student_competencies[!is.na(student_competencies$code),]
  #print(knitr::kable(student_competencies, format="html"))
  # get the badge numbers - it is possible for more than one
  
  s_badge <- unique(student_competencies$Badge.Number)
  s_badge <- paste(na.omit(s_badge))
  # when there are no scans, the badge will not occur in this loop so the above 2 lines don't work. Should be able to remove them - badge is now found by a more reliable method below.
  s_badge_from_IDmapping <- ID_mapping[ID_mapping$student_ID==student,"Badge.Number"]
  scan_count <- sum(scanner_reads$scan==s_badge_from_IDmapping)
  scan_count <- nrow(student_competencies)
  
  # remove badge number from the table because there is no need to report it further
  student_competencies <- student_competencies[,-6]
  
  # identify skills by group
  student_skills_groups <- unique(student_competencies$skill.group)
  cat("##",s_name, "\n\n")

  cat("Hello ",s_name,"(ID ",student,"; Badge ",s_badge_from_IDmapping,"; Number of scans logged:",scan_count,")\n\n","

Here is a report on the skills we have recorded for you. You can use this report to assist in your skills related assessments, for your personal development planning, and for developing your CV etc.\n\n * Where the date is listed as NA this means it is a manual record such as being attendance based or to correct for forgotten card etc.\n\n* In the E column `E` indicates `essential` competencies and `S` indicates `Specialist` which means they are not part of core teaching but you might get opportunities to pursue e.g. through your IS or optional sessions. There are normally about 3 essential competencies per skill group and you need all the essential ones to reach the `basic` level of achievement.\n\n * At level 4 students should achieve 3 skill groups to basic level - evidenced by 3 essential competencies in 3 different skill groups (i.e. minimum of 9 competencies).\n\n* At level 5 students should build 2 skill groups up to intermediate level by achieving 6 competencies in them whilst also broadening the base of basic skills.\n\n* In level 6 students should be evidenvcing the development of advanced skills in some areas, defined by gaining 9 different competencies in any skill group.
\n\n
")
  
  if(length(s_badge_from_IDmapping)<1) {
   cat("\n<b>We do not have a record of your badge number. This means your skills report is based only on manual records and not including any badge scans you may have had. Please contact your personal tutor and inform them of your badge number.</b>\n\n") 
  }

  cat("###","Your verified competency observations\n")

  for(skill_group in student_skills_groups) {
    # skill_group <- student_skills_groups[1] for testing
    cat("####","Competencies in skill group -", skill_group,"\n")
    index <- student_competencies$skill.group==skill_group
    print(knitr::kable(student_competencies[index,-4], format="html") %>% kable_styling(bootstrap_options = c("striped", "hover"))) 
  }
  
  # student_competencies <- matched_reads[matched_reads$student_ID==student,c("observed_competency")]
  # classify skills
  cat("<br>\n\n Kind regards <br>\n Your teaching team\n<hr>")
}

```

```{r output-files, echo=FALSE}
# classify skills - alternative way 
matched_reads2 <- merge(matched_reads,competencies,by.x="observed_competency",by.y="Competency")
#unmatched_reads2 <- merge(unmatched_reads,competencies,by.x="observed_competency",by.y="Competency")
# report of student attainment:
matched_table <- as.data.frame((matched <- with(matched_reads2, table(student_ID, observed_competency))))
#with(matched_reads2, table(Name, observed_competency))
#(matched <- with(matched_reads2, table(Name, observed_competency)))

fname <- "d:/git/skills-passport/output/ID_competencies.csv"
write.csv(x = matched, file = fname)


# I want to add the student names to the above
# this doesn't quite work but nearly
#matched <- as.data.frame(matched)

matched.named <- merge(matched,ID_mapping,by.x="student_ID",by.y="student_ID")

matched_table.named <- as.data.frame((matched.named.table <- with(matched.named, table(student_ID,Name, observed_competency))))

fname.named <- "d:/git/skills-passport/output/ID_competencies_named.csv"
write.csv(x = matched.named.table, file = fname.named)



matched.named <- merge(matched,ID_mapping,by.x="student_ID",by.y="student_ID")
matched.named <- matched.named[matched.named$Freq>0,c("student_ID","Name","observed_competency","Freq")]


# get a report of all competencies by badge number (note that student_ID is actually badge number here)
#badge_competencies <- with(all_reads, table(Badge.Number, observed_competency))
#fname <- "d:/git/skills-passport/output/badge_competencies.csv"
#write.csv(x = badge_competencies, file = fname)

```

